# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-19 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='An',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=32, verbose_name='处理池编号')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('measure_nub', models.DecimalField(decimal_places=2, default=0, max_digits=5, max_length=32, verbose_name='测量数值')),
                ('name', models.CharField(max_length=32, verbose_name='数据名称')),
                ('sendor', models.CharField(max_length=32, verbose_name='传感器编号')),
                ('is_status', models.BooleanField(default=True, verbose_name='是否达标')),
                ('measure_at', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
            ],
            options={
                'db_table': 'an',
            },
        ),
        migrations.CreateModel(
            name='AnAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=32, verbose_name='处理池编号')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('measure_nub', models.DecimalField(decimal_places=2, default=0, max_digits=5, max_length=32, verbose_name='测量数值')),
                ('sendor', models.CharField(max_length=32, verbose_name='传感器编号')),
                ('is_handle', models.BooleanField(default=False, verbose_name='是否处理')),
                ('measure_at', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
                ('handle_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('handle_no', models.SmallIntegerField(verbose_name='处理员工ID')),
                ('status', models.CharField(max_length=32, verbose_name='报警类型')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.An')),
            ],
            options={
                'db_table': 'an_alert',
            },
        ),
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=32, verbose_name='处理池编号')),
                ('equip', models.CharField(max_length=32, verbose_name='设备号')),
                ('equip_status', models.SmallIntegerField(choices=[(1, '正常状态'), (2, '维修状态'), (3, '添加药物')], default=1, verbose_name='处理状态')),
                ('status_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='测量时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'db_table': 'equip',
            },
        ),
        migrations.CreateModel(
            name='EquipAlertRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=32, verbose_name='处理池编号')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('handle_no', models.SmallIntegerField(verbose_name='处理员工ID')),
                ('status', models.SmallIntegerField(choices=[(1, '设备维修'), (2, '药物不足')], default=2, verbose_name='设备报警类型')),
                ('is_handle', models.BooleanField(default=False, verbose_name='是否处理')),
                ('handle_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('equip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.Equip')),
            ],
            options={
                'db_table': 'equip_alert',
            },
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=32, verbose_name='处理池编号')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('measure_nub', models.DecimalField(decimal_places=2, default=0, max_digits=5, max_length=32, verbose_name='测量数值')),
                ('name', models.CharField(max_length=32, verbose_name='数据名称')),
                ('sendor', models.CharField(max_length=32, verbose_name='传感器编号')),
                ('is_status', models.BooleanField(default=True, verbose_name='是否达标')),
                ('measure_at', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
            ],
            options={
                'db_table': 'metal',
            },
        ),
        migrations.CreateModel(
            name='MetalAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=32, verbose_name='处理池编号')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('measure_nub', models.DecimalField(decimal_places=2, default=0, max_digits=5, max_length=32, verbose_name='测量数值')),
                ('sendor', models.CharField(max_length=32, verbose_name='传感器编号')),
                ('is_handle', models.BooleanField(default=False, verbose_name='是否处理')),
                ('handle_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('measure_at', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
                ('handle_no', models.SmallIntegerField(verbose_name='处理员工ID')),
                ('status', models.CharField(max_length=32, verbose_name='报警类型')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.Metal')),
            ],
            options={
                'db_table': 'metal_alert',
            },
        ),
        migrations.CreateModel(
            name='PH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=32, verbose_name='处理池编号')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('measure_nub', models.DecimalField(decimal_places=2, default=0, max_digits=5, max_length=32, verbose_name='测量数值')),
                ('name', models.CharField(max_length=32, verbose_name='数据名称')),
                ('sendor', models.CharField(max_length=32, verbose_name='传感器编号')),
                ('is_status', models.BooleanField(default=True, verbose_name='是否达标')),
                ('measure_at', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
            ],
            options={
                'db_table': 'ph',
            },
        ),
        migrations.CreateModel(
            name='PHAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=32, verbose_name='处理池编号')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('measure_nub', models.DecimalField(decimal_places=2, default=0, max_digits=5, max_length=32, verbose_name='测量数值')),
                ('sendor', models.CharField(max_length=32, verbose_name='传感器编号')),
                ('is_handle', models.BooleanField(default=False, verbose_name='是否处理')),
                ('measure_at', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
                ('handle_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('handle_no', models.SmallIntegerField(verbose_name='处理员工ID')),
                ('status', models.CharField(max_length=32, verbose_name='报警类型')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.PH')),
            ],
            options={
                'db_table': 'ph_alert',
            },
        ),
        migrations.CreateModel(
            name='Solid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=32, verbose_name='处理池编号')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('measure_nub', models.DecimalField(decimal_places=2, default=0, max_digits=5, max_length=32, verbose_name='测量数值')),
                ('name', models.CharField(max_length=32, verbose_name='数据名称')),
                ('sendor', models.CharField(max_length=32, verbose_name='传感器编号')),
                ('is_status', models.BooleanField(default=True, verbose_name='是否达标')),
                ('measure_at', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
            ],
            options={
                'db_table': 'solid',
            },
        ),
        migrations.CreateModel(
            name='SolidAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=32, verbose_name='处理池编号')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('measure_nub', models.DecimalField(decimal_places=2, default=0, max_digits=5, max_length=32, verbose_name='测量数值')),
                ('sendor', models.CharField(max_length=32, verbose_name='传感器编号')),
                ('is_handle', models.BooleanField(default=False, verbose_name='是否处理')),
                ('handle_at', models.DateTimeField(auto_now_add=True, verbose_name='处理时间')),
                ('measure_at', models.DateTimeField(auto_now_add=True, verbose_name='测量时间')),
                ('handle_no', models.SmallIntegerField(verbose_name='处理员工ID')),
                ('status', models.CharField(max_length=32, verbose_name='报警类型')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analysis.Solid')),
            ],
            options={
                'db_table': 'solid_alert',
            },
        ),
    ]
