# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-21 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_selectcell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectcell',
            name='select_cell',
            field=models.CharField(choices=[('1-1', '初次沉淀池'), ('1-2', '1号过滤池'), ('1-2', '二次沉淀池'), ('2-1', '2号沉淀池'), ('2-2', '重金属吸收池'), ('2-3', '2号过滤池'), ('3-1', '氨氮吸收池'), ('3-2', '氨氮吸收池')], max_length=10),
        ),
    ]
