# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-05-04 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('username', models.CharField(max_length=64, verbose_name='账户号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('level', models.SmallIntegerField(choices=[(1, '普通员工'), (2, '主管')], default=1, verbose_name='级别')),
                ('login_status', models.BooleanField(default=False, verbose_name='登陆状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'administration_user',
            },
        ),
    ]
